### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Daewooo** [JunJianSyu/wap-alipay#1]
![image](https://cloud.githubusercontent.com/assets/6645249/8637511/ce8bc078-28c6-11e5-952e-bc25850bdea7.png)

**Comment by JunJianSyu** [comment]
你自身传参的问题 我这边根据你的问题我测试了一遍程序是没问题！非常感谢你对此项目的关注

**Comment by fritx** [comment]
res_xmlss报错 输出xmlstr 发现返回`缺少了非空的业务参数` 咋整？

![image](https://cloud.githubusercontent.com/assets/6647633/16080031/58984cdc-3339-11e6-8910-e3eeb98cc652.png)

**Comment by JunJianSyu** [comment]
确认Pay_Config配置没有问题，生成订单金额和信息无误后测试。这个错误信息是alipay没有接收到参数导致的。具体什么参数我没看到你修改的code无法回答你的问题。
